version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: app_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  php:
    build:
      context: ./docker/php
    container_name: app_php
    volumes:
      - ./app:/var/www/html
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: app_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: proyecto_db
      MYSQL_USER: proyecto_user
      MYSQL_PASSWORD: proyecto_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_pass
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge